I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 48, in script
    with fade
OSError: Couldn't find file 'game/audio/city.ogg'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 48, in script
    with fade
  File "C:\Users\blood\Pirated\renpy\renpy-8.1.3-sdk\renpy\ast.py", line 1678, in execute
    renpy.exports.with_statement(trans, paired=paired)
  File "C:\Users\blood\Pirated\renpy\renpy-8.1.3-sdk\renpy\exports.py", line 1758, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "C:\Users\blood\Pirated\renpy\renpy-8.1.3-sdk\renpy\display\core.py", line 2978, in do_with
    return self.interact(trans_pause=True,
  File "C:\Users\blood\Pirated\renpy\renpy-8.1.3-sdk\renpy\display\core.py", line 3582, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "C:\Users\blood\Pirated\renpy\renpy-8.1.3-sdk\renpy\display\core.py", line 4379, in interact_core
    renpy.audio.audio.periodic()
  File "C:\Users\blood\Pirated\renpy\renpy-8.1.3-sdk\renpy\audio\audio.py", line 1224, in periodic
    raise_(exc[0], exc[1], exc[2])
  File "/home/tom/ab/renpy-build-fix/tmp/install.linux-x86_64/lib/python3.9/site-packages/future/utils/__init__.py", line 444, in raise_
  File "C:\Users\blood\Pirated\renpy\renpy-8.1.3-sdk\renpy\audio\audio.py", line 1202, in periodic_thread_main
    periodic_pass()
  File "C:\Users\blood\Pirated\renpy\renpy-8.1.3-sdk\renpy\audio\audio.py", line 1144, in periodic_pass
    c.periodic()
  File "C:\Users\blood\Pirated\renpy\renpy-8.1.3-sdk\renpy\audio\audio.py", line 534, in periodic
    topf = load(filename)
  File "C:\Users\blood\Pirated\renpy\renpy-8.1.3-sdk\renpy\audio\audio.py", line 72, in load
    rv = renpy.loader.load(fn, directory="audio")
  File "C:\Users\blood\Pirated\renpy\renpy-8.1.3-sdk\renpy\loader.py", line 833, in load
    raise IOError("Couldn't find file '%s'." % name)
OSError: Couldn't find file 'game/audio/city.ogg'.

Windows-10-10.0.19041 AMD64
Ren'Py 8.1.3.23091805
EmoCat 1.0
Sun Nov  5 17:25:42 2023
